name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Adjust as needed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubernetes config
        run: |
          echo "Setting up Kubernetes config"
          mkdir -p $HOME/.kube
          echo "apiVersion: v1" > $HOME/.kube/config
          echo "clusters:" >> $HOME/.kube/config
          echo "- cluster:" >> $HOME/.kube/config
          echo "    server: $KUBE_HOST" >> $HOME/.kube/config
          if [ -n "$KUBE_CERTIFICATE" ]; then
            echo "    certificate-authority-data: $KUBE_CERTIFICATE" >> $HOME/.kube/config
          fi
          echo "  name: k8s" >> $HOME/.kube/config
          echo "contexts:" >> $HOME/.kube/config
          echo "- context:" >> $HOME/.kube/config
          echo "    cluster: k8s" >> $HOME/.kube/config
          echo "    user: github-actions" >> $HOME/.kube/config
          echo "  name: github-actions" >> $HOME/.kube/config
          echo "current-context: github-actions" >> $HOME/.kube/config
          echo "users:" >> $HOME/.kube/config
          echo "- name: github-actions" >> $HOME/.kube/config
          echo "  user:" >> $HOME/.kube/config
          echo "    token: $KUBE_TOKEN" >> $HOME/.kube/config
          
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yaml
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}

