name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Adjust as needed
jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
