name: VPN Connection
on:
  push:
    branches:
      - main

jobs:
  connect-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install -y network-manager-l2tp network-manager-l2tp-gnome
          git clone https://github.com/vareger/l2tp-client.git
          cd l2tp-client
          sudo ./connect_vpn.sh
      
                
      - name: setup-vpn-client-meraki
        uses: matcontardo/setup-vpn-client-meraki@1.5
        with:
          server: 172.240.241.200  # Replace with your actual VPN server
          username: DevOps-VPN          # Your VPN username
          password: yY2y7wsDwG44          # Your VPN password
          psk: mMJ9m8Z5ynG4
          # Add more input variables as needed

# jobs:
#   deploy:
#     runs-on: self-hosted  
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
        
#       - uses: actions-hub/kubectl@master
#         env:
#           KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#         with:
#           args: get pods
#       - name: checking manifest files
#         run: pwd && ls -la
#       - name: k8s
#         run: |
#              kubectl apply -f namespace.yaml
#              kubectl apply -f configmap.yaml
#              kubectl apply -f deployment.yaml
#              kubectl apply -f service.yaml

