name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Validate kubeconfig
      run: |
        kubectl config view
        kubectl config get-contexts


    - uses: actions-hub/kubectl@master
      env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
          args: get pods

    - name: Deploy to K8s
      run: kubectl apply -f ./
