name: Deploy to Kubeadm Kubernetes Cluster

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up Kubeconfig
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_FILE }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG_FILE}" > $HOME/.kube/config

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./
