name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
          chmod 600 ${HOME}/.kube/config
      
      - name: Verify kubeconfig size
        run: |
          echo "Kubeconfig size: $(wc -c < ${HOME}/.kube/config)"
          cat ${HOME}/.kube/config  # Uncomment to see the content (only for debugging)
      
      - name: Validate kubeconfig
        run: |
          kubectl config view
          kubectl config get-contexts

      - name: Test API Connectivity
        run: |
          kubectl get all -A

      - name: Deploy to K8s
        run: |
          kubectl apply -f ./
