name: VPN Connection

on:
  push:
    branches:
      - main

jobs:
  connect-vpn:
    runs-on: ubuntu-latest
    env:
      VPN_SERVER: ${{ secrets.VPN_SERVER }}
      VPN_USER: ${{ secrets.VPN_USER }}
      VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      VPN_PSK: ${{ secrets.VPN_PSK }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install VPN Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq strongswan libcharon-extra-plugins

      - name: Run VPN Connection Script
        run: |
          chmod +x ./l2tp.sh
          ./l2tp.sh
        env:
          VPN_SERVER: ${{ secrets.VPN_SERVER }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
          VPN_PSK: ${{ secrets.VPN_PSK }}

      - name: Verify Connection
        run: |
          ip a
          echo "Connected to VPN successfully!"

      - name: Disconnect VPN
        if: always()
        run: |
          sudo ipsec down my-l2tp || echo "VPN already disconnected."
          echo "Disconnected VPN."
