name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Adjust as needed
jobs:
  deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
      - name: checking manifest files
        run: ls -la
      - name: k8s
        run: kubectl get all -A
