name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update apt repository
        run: sudo apt-get update -y

      - name: Install prerequisites
        run: sudo apt-get install -y apt-transport-https ca-certificates curl gnupg

      - name: Add Kubernetes APT key
        run: |
          curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

      - name: Add Kubernetes APT repository
        run: |
          echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

      - name: Update apt repository again
        run: sudo apt-get update

      - name: Install kubectl
        run: sudo apt-get install -y kubectl

      - name: Check kubectl version
        run: kubectl version --client

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f namespace.yaml
          kubectl apply -f configmap.yaml
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f hpa.yaml
